# Generated by Django 5.2.4 on 2025-07-23 02:26

import django.db.models.deletion
import reimbursement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('reason', models.CharField(max_length=255, verbose_name='报销事由')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('invoice_pdf', models.FileField(upload_to=reimbursement.models.get_invoice_path, verbose_name='发票PDF')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=10, verbose_name='审核状态')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='不通过理由')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
        ),
    ]
