# Generated by Django 5.2.9 on 2025-12-31 08:24

import reimbursement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to=reimbursement.models.get_invoice_path, verbose_name='发票PDF'),
        ),
    ]
