# Generated by Django 5.2.9 on 2026-01-05 01:42

import reimbursement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_alter_reimbursementrequest_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementrequest',
            name='is_taxi_invoice',
            field=models.BooleanField(default=False, verbose_name='是否为打车发票'),
        ),
        migrations.AddField(
            model_name='reimbursementrequest',
            name='itinerary_pdf',
            field=models.FileField(blank=True, null=True, upload_to=reimbursement.models.get_itinerary_path, verbose_name='行程单PDF'),
        ),
    ]
