# Generated by Django 5.2.9 on 2026-01-07 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_reimbursementrequest_is_taxi_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='记账日期')),
                ('entry_type', models.CharField(choices=[('reimbursement', '报销支出'), ('income', '收入'), ('expense', '其他支出')], default='reimbursement', max_length=20, verbose_name='类型')),
                ('real_name', models.CharField(max_length=100, verbose_name='提交人姓名')),
                ('reason', models.CharField(max_length=255, verbose_name='事由')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('reimbursement', models.ForeignKey(blank=True, help_text='如果是从报销申请自动生成的，会有关联', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reimbursement.reimbursementrequest', verbose_name='关联报销申请')),
            ],
            options={
                'verbose_name': '财务记账本',
                'verbose_name_plural': '财务记账本',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
